/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Directory Meta
         * @description Дата/время последней загрузки копии витрин (app.load_log, БТ 2.2 / 2.5.3).
         */
        get: operations["directory_meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search Clients
         * @description Подсказки по ИНН (префикс) или наименованию (подстрока; нечёткий запасной путь).
         */
        get: operations["search_clients_api_clients_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{inn}/limits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Client Limits
         * @description Установленные лимиты и заявки: t_lm_1_3_limits + comment_egar + единые показатели.
         */
        get: operations["client_limits_api_clients__inn__limits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/clients/{inn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Client Card
         * @description Карточка клиента: одна строка t_lm_1_2_clients на ИНН.
         */
        get: operations["client_card_api_clients__inn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/groups/{crm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Group Card
         * @description Карточка ГК: t_lm_1_2_gk_info (MAX уровня ГК, SUM клиентских строк, по валютам).
         */
        get: operations["group_card_api_groups__crm_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClientCard
         * @description Карточка клиента: одна строка t_lm_1_2_clients на ИНН.
         */
        ClientCard: {
            /** Inn */
            inn: string;
            /** Name */
            name?: string | null;
            /** Code */
            code?: string | null;
            /** Ogrn */
            ogrn?: string | null;
            /** Kpp */
            kpp?: string | null;
            /** Address */
            address?: string | null;
            /** Okved */
            okved?: string | null;
            /** Source */
            source?: string | null;
            group?: components["schemas"]["GroupRef"] | null;
            /**
             * Groups Found
             * @default 0
             */
            groups_found: number;
        };
        /**
         * ClientShort
         * @description Строка подсказки поиска: t_lm_1_2_clients.
         */
        ClientShort: {
            /** Inn */
            inn: string;
            /** Name */
            name?: string | null;
            /** Kpp */
            kpp?: string | null;
        };
        /** GroupCard */
        GroupCard: {
            /** Crm Id */
            crm_id: string;
            /** Name */
            name?: string | null;
            /** Summaries */
            summaries: components["schemas"]["GroupSummary"][];
            /** Members */
            members: components["schemas"]["GroupMember"][];
        };
        /** GroupMember */
        GroupMember: {
            /** Inn */
            inn: string;
            /** Name */
            name?: string | null;
            /** Currency */
            currency?: string | null;
            /** Unified Limit */
            unified_limit?: string | null;
            /** Unified Utilized */
            unified_utilized?: string | null;
            /** Unified Available */
            unified_available?: string | null;
            /**
             * Has Card
             * @default false
             */
            has_card: boolean;
        };
        /**
         * GroupRef
         * @description Ссылка на ГК клиента: t_lm_1_2_gk_info (fallback t_lm_1_3_limits.gk_*).
         */
        GroupRef: {
            /** Crm Id */
            crm_id: string;
            /** Name */
            name?: string | null;
        };
        /**
         * GroupSummary
         * @description Сводка ГК по одной валюте: t_lm_1_2_gk_info GROUP BY group_crm_id1, currency.
         */
        GroupSummary: {
            /** Currency */
            currency?: string | null;
            /** Members */
            members: number;
            /** Total Limit */
            total_limit?: string | null;
            /** Total Utilized */
            total_utilized?: string | null;
            /** Total Available */
            total_available?: string | null;
            /** Unified Limit */
            unified_limit?: string | null;
            /** Unified Utilized */
            unified_utilized?: string | null;
            /** Unified Available */
            unified_available?: string | null;
            /**
             * Is Exceeded
             * @default false
             */
            is_exceeded: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LimitRow
         * @description Строка t_lm_1_3_limits (+ comment_egar из t_lm_egar_limits для ИБ).
         */
        LimitRow: {
            /** Limit Id */
            limit_id?: string | null;
            /** Owner */
            owner?: string | null;
            /** Product */
            product?: string | null;
            /** Currency */
            currency?: string | null;
            /** Status */
            status?: string | null;
            /**
             * Status Code
             * @default unknown
             * @enum {string}
             */
            status_code: "active" | "inactive" | "pending" | "unknown";
            /** Src Status */
            src_status?: string | null;
            /** Start Date */
            start_date?: string | null;
            /** End Date */
            end_date?: string | null;
            /** Rate */
            rate?: string | null;
            /** Lim Value */
            lim_value?: string | null;
            /** Lim Utiled */
            lim_utiled?: string | null;
            /** Rest Lim */
            rest_lim?: string | null;
            /** Client Limits */
            client_limits?: string | null;
            /** Lim Top */
            lim_top?: string | null;
            /** Client Raroc */
            client_raroc?: string | null;
            /** Comment */
            comment?: string | null;
            /**
             * Is Exceeded
             * @default false
             */
            is_exceeded: boolean;
        };
        /** LimitsResponse */
        LimitsResponse: {
            /** Inn */
            inn: string;
            /** Client Name */
            client_name?: string | null;
            /** Limits */
            limits: components["schemas"]["LimitRow"][];
            /** Applications */
            applications: components["schemas"]["LimitRow"][];
            /** Unified */
            unified: components["schemas"]["UnifiedRow"][];
        };
        /**
         * Meta
         * @description Актуальность копии: app.load_log (БТ 2.2 / 2.5.3).
         */
        Meta: {
            /** Updated At */
            updated_at?: string | null;
            /** Data Date */
            data_date?: string | null;
            /**
             * Stale
             * @default true
             */
            stale: boolean;
            /**
             * Stale After Hours
             * @default 24
             */
            stale_after_hours: number;
        };
        /**
         * UnifiedRow
         * @description Единые показатели клиента по валюте: t_lm_1_2_gk_info WHERE party_inn = :inn.
         */
        UnifiedRow: {
            /** Group Crm Id */
            group_crm_id?: string | null;
            /** Group Name */
            group_name?: string | null;
            /** Currency */
            currency?: string | null;
            /** Unified Limit */
            unified_limit?: string | null;
            /** Unified Utilized */
            unified_utilized?: string | null;
            /** Unified Available */
            unified_available?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    directory_meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    search_clients_api_clients_get: {
        parameters: {
            query: {
                q: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientShort"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_limits_api_clients__inn__limits_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LimitsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_card_api_clients__inn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                inn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClientCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    group_card_api_groups__crm_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                crm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GroupCard"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
